// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// T
double T(NumericVector xi, NumericVector xj);
RcppExport SEXP codmeR_T(SEXP xiSEXP, SEXP xjSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type xi(xiSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type xj(xjSEXP );
        double __result = T(xi, xj);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fastaitvar
NumericMatrix fastaitvar(NumericMatrix x);
RcppExport SEXP codmeR_fastaitvar(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        NumericMatrix __result = fastaitvar(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
