# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute Hamming distance
#' @param xi NumericVector with data
#' @param xj NumericVector with data
#' @return symmetric matrix with pairwise Aitchison variations
Hamdist <- function(xi, xj) {
    .Call('codmeR_Hamdist', PACKAGE = 'codmeR', xi, xj)
}

#' compute Hamming distance of matrix cols quickly
#' @param x NumericMatrix with data
#' @return symmetric matrix with pairwise Aitchison variations
HamdistMat <- function(x) {
    .Call('codmeR_HamdistMat', PACKAGE = 'codmeR', x)
}

coCalc <- function(xi, xj, sumint = 2L) {
    .Call('codmeR_coCalc', PACKAGE = 'codmeR', xi, xj, sumint)
}

coCalcMat <- function(x, sumint = 2L) {
    .Call('codmeR_coCalcMat', PACKAGE = 'codmeR', x, sumint)
}

#' compute Cooccurance
#' @param xi NumericVector with data
#' @param xj NumericVector with data
#' @return symmetric matrix with pairwise Aitchison variations
cooccurMat <- function(x) {
    .Call('codmeR_cooccurMat', PACKAGE = 'codmeR', x)
}

#' compute Coabsence
#' @param xi NumericVector with data
#' @param xj NumericVector with data
#' @return symmetric matrix with pairwise Aitchison variations
coabsenceMat <- function(x) {
    .Call('codmeR_coabsenceMat', PACKAGE = 'codmeR', x)
}

fastaitvar <- function(A) {
    .Call('codmeR_fastaitvar', PACKAGE = 'codmeR', A)
}

