# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute aitchison variation of matrix cols quickly
#' @param x NumericMatrix with data
#' @return symmetric matrix with pairwise Aitchison variations
fastaitvar <- function(x) {
    .Call('codmeR_fastaitvar', PACKAGE = 'codmeR', x)
}
